### ISSUE TITLE
AzurePipelinesDataError on valid expression syntax

### ISSUE THREAD

**Issue by robertaves** [python-jsonschema/check-jsonschema#162]
Looking to validate my Azure pipelines and have run into a blocker.  I currently have a pipeline in production ( working and running ) with the following syntax

     steps:
          - bash: |         
              pipenv run pip install ansible-lint-junit --upgrade
              pipenv run ansible-lint -c ../.config/ansible-lint.yml -p --nocolor > ansible-lint.txt
              pipenv run ansible-lint-junit ansible-lint.txt -o AnsibleLintReport.xml
            displayName: "Lint"
            workingDirectory: ${{parameters.workdir}}
            env:
              ${{ each pair in parameters.env }}:
                ${{ pair.key }}: ${{ pair.value }}

when running with the pre-commit hook

            - repo: https://github.com/python-jsonschema/check-jsonschema
              rev: 0.18.3
              hooks:
                - id: check-azure-pipelines
                  files: '^.azure/.*\.yml'
it currently raises the error 

      raise AzurePipelinesDataError(
      check_jsonschema.transforms.azure_pipelines.AzurePipelinesDataError: azure-pipelines transform: found non-object data under an expression in an object, expression=${{ pair.key }}

**Comment by sirosen** [comment]
I've just released v0.18.4 which ought to fix this issue. Please let me know if the fix doesn't work for you or if you're seeing other problems with the Azure Pipelines handling!
