### ISSUE TITLE
Error: schemafile could not be parsed as JSON

### ISSUE THREAD

**Issue by blink1073** [python-jsonschema/check-jsonschema#183]
We occasionally see this error in [CI](https://github.com/jupyter-server/jupyter_server/actions/runs/3465618145/jobs/5788571563#step:4:208), and it usually works when we kick the build.

```python
Error: schemafile could not be parsed as JSON
SchemaParseError: https://json.schemastore.org/github-workflow
  in "/home/runner/.cache/pre-commit/repo72xvbo31/py_env-python3.10/lib/python3.10/site-packages/check_jsonschema/checker.py", line 50
  >>> return self._schema_loader.get_validator(path, doc, self._format_opts)

  caused by

  JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    in "/home/runner/.cache/pre-commit/repo72xvbo31/py_env-python3.10/lib/python3.10/site-packages/check_jsonschema/schema_loader/readers.py", line 18
    >>> schema = callback()

    caused by

    StopIteration: 0
      in "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/json/decoder.py", line 353
      >>> obj, end = self.scan_once(s, idx)
ok -- validation done

Error: Process completed with exit code 1.
```

Perhaps adding retry logic would address the issue.

**Comment by sirosen** [comment]
(Aside: It's not related to the core issue, but it's weird that the `ok` message was printed on a failure. I'll have to look into that as a separate matter.)

To understand your usage, I took a look at your config. Just to ensure we're on the same page, here's what you're running in `jupyter_server`:
```yaml
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.18.4
    hooks:
      - id: check-jsonschema
        name: "Check GitHub Workflows"
        files: ^\.github/workflows/
        types: [yaml]
        args: ["--schemafile", "https://json.schemastore.org/github-workflow"]
        stages: [manual]
```

That's a bit different from what I'm recommending these days, so I first want to make sure we're on the same page about the behaviors and that you're getting what you want and expect. Here's what I document for checking github workflows:
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.19.1
  hooks:
    - id: check-github-workflows
```

I don't mean to suggest that your config is wrong; it's just different. You'll always get the latest schema from schemastore (well, you _should_, the bug report is that you don't! 😅 ), whereas the `check-github-workflows` hook uses a vendored copy of the schemastore schema. On the one hand, always getting the latest from schemastore means that you're not dependent on `check-jsonschema` releases to ship updates. On the other hand, it means that the behavior of the hook can change between two runs on the same version number, which could be confusing or surprising.

---

All that aside, I can definitely do something to improve the download behavior.

This is just a guess, but I've at least once seen schemastore respond with an empty 200.
I'm thinking that I need to make the following adjustments:
- add support to the downloader piece to do a validation callback
- if the validation callback fails, the download retries once or twice (2 retries seems like a reasonable start to me)
- pass a parse function, e.g. `json.load` as the validation callback

**Comment by blink1073** [comment]
Thanks @sirosen!  I'm happy to update to the new recommended workflow.

**Comment by sirosen** [comment]
Awesome, glad I could offer a helping hand!

I'm keeping this open though, since I still think that download behavior has room for improvement.

**Comment by blink1073** [comment]
Yep, sounds good.  Here's the PR for anyone interested: https://github.com/jupyter-server/jupyter_server/pull/1071.  A nice benefit is that it can run in the `pre-commit.ci` job since it doesn't need access to the internet.
