### ISSUE TITLE
check-jsonschema cli fails with AttributeError

### ISSUE THREAD

**Issue by DSuveges** [python-jsonschema/check-jsonschema#229]
I have installed check-jsonschema but cli fails with:

**Traceback:**
```
╰─ /Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/bin/check-jsonschema
Traceback (most recent call last):
  File "/Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/bin/check-jsonschema", line 5, in <module>
    from check_jsonschema import main
  File "/Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/lib/python3.8/site-packages/check_jsonschema/__init__.py", line 3, in <module>
    from .cli import main
  File "/Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/lib/python3.8/site-packages/check_jsonschema/cli.py", line 10, in <module>
    from .checker import SchemaChecker
  File "/Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/lib/python3.8/site-packages/check_jsonschema/checker.py", line 10, in <module>
    from .formats import FormatOptions
  File "/Users/dsuveges/.pyenv/versions/3.8.15/envs/evidence_parsers/lib/python3.8/site-packages/check_jsonschema/formats.py", line 11, in <module>
    "http://json-schema.org/draft-03/schema#": jsonschema.Draft3Validator.FORMAT_CHECKER,
AttributeError: type object 'Draft3Validator' has no attribute 'FORMAT_CHECKER'
```

python: 3.8.15
check-jsonschema: 0.20.0

**Installation via pip went well:**

```
╰─ pip install check-jsonschema
Collecting check-jsonschema
  Downloading check_jsonschema-0.20.0-py3-none-any.whl (195 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.7/195.7 KB 4.9 MB/s eta 0:00:00
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, check-jsonschema
Successfully installed check-jsonschema-0.20.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7
```

I would be very grateful if you could advise on what I should do or further check.

**Comment by sirosen** [comment]
I think you've installed into an environment with an old version of `jsonschema`, and the `check-jsonschema` bound on versions is not tight enough. (`FORMAT_CHECKER` is a newer attribute.)

Could you share the version you're using? e.g. `pip list | grep jsonschema`

Even if you upgrade and it fixes things, I'd like to know the version to make sure of things. Thanks!

**Comment by sirosen** [comment]
I plan to check when `FORMAT_CHECKER` was introduced and increase the min version bound to help avoid this situation in the next release, by the way.

**Comment by DSuveges** [comment]
Thank you for the super quick response! I really appreciate it. 

So this is the output:
```
check-jsonschema         0.20.0
fastjsonschema           2.16.2
jsonschema               4.4.0
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
```

I guess I try to update the other packages as well. Thanks for the tip!

**Comment by DSuveges** [comment]
OK. that was it. After updating jsonschema, it works. You can consider setting a fixed version as a dependency.

**Comment by sirosen** [comment]
I updated the lower bound and added some testing to hopefully avoid this kind of issue in the future.
Again, thanks for reporting it!

As soon as I finish the release I'm working on, a new version (0.21.0) will be available with the fixed lower bound.

**Comment by DSuveges** [comment]
Great! Thank you!
