### ISSUE TITLE
Add support for unknown field validation

### ISSUE THREAD

**Issue by piyushmor** [python-jsonschema/check-jsonschema#254]
support needed for respecting `additionalProperties:false`. Currently there is no option to make the validation respect this.

**Comment by sirosen** [comment]
Hi there! `additionalProperties` should be well supported by the underlying JSON Schema library, and I've never seen a case of it evaluating incorrectly.

Could you share an example of a schema and instance that do not demonstrate the behavior which you want?

**Comment by sirosen** [comment]
On further thought, I see no reason not to close this. The requested feature already exists and works correctly to the best of my knowledge.

If there's a bug report with a reproducible example, that would probably be a new issue.
