### ISSUE TITLE
Output of all validated files if verbose: true

### ISSUE THREAD

**Issue by tschm** [python-jsonschema/check-jsonschema#312]
I would love to see in the output a list of those files that been picked up by your tool and validated.
Maybe it's already possible. I am a new user.

**Comment by sirosen** [comment]
That's a good idea! It's not available today but it makes perfect sense.

I'll need to do some work to make sure the JSON output also includes this info, so it's not quite as simple as just printing the files as they're checked, but it shouldn't be hard.

**Comment by sirosen** [comment]
This should now be available in v0.26.2!

Please let me know if it's insufficient for your needs or if you run into any trouble with `check-jsonschema`.

**Comment by tschm** [comment]
It works. However, you may want to check whether you really need both the verbose: true and the args: ["--verbose"] construct... Many thanks for this

**Comment by sirosen** [comment]
`check-jsonschema` is not responsible for the pre-commit verbosity option to which you are referring. Only two verbosity options are defined by this tool: `-q/--quiet` and `-v/--verbose`.
