### ISSUE TITLE
Support new GitHub Actions Runner Scale Sets

### ISSUE THREAD

**Issue by stephen-tatari** [python-jsonschema/check-jsonschema#345]
For reference: https://github.com/SchemaStore/schemastore/issues/3192

To run a workflow on a self-hosted runner created as part of Runner Scale Sets, the value for `runs-on` must be one of:
* a single string
* a list with a single string entry
* an expression (e.g., `${{matrix.runer}}`)

The old way of running on self-hosted runners was to have a list with `self-hosted` as the first element. That's no longer supported with Runner Scale Sets.

I got a PR merged on https://github.com/SchemaStore/schemastore to address this, and I believe all this needs is a new release with a schema update for https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json.

**Comment by sirosen** [comment]
Yep; that's exactly what's needed! I just need to pull in schema updates and cut a release.
I'll get to it later today or tomorrow -- it's easy, but I need to close out some other work first.

Thanks for pinging here about it; I'm always happy to do releases in response to user needs! :smile:

**Comment by sirosen** [comment]
Sorry for the delay after I said I'd do this more or less right away. A combination of factors slowed me down, but v0.27.1 is out and should have the new schema ready for use!

Please let me know if you see any issues with it!
(And minor FYI, I'll be offline for a couple of weeks starting this weekend, so there may be slower response times on any issues.)
