### ISSUE TITLE
Update vendored bitbucket schema

### ISSUE THREAD

**Issue by blade2005** [python-jsonschema/check-jsonschema#360]
There's an updated version of their schema here
https://bitbucket.org/atlassianlabs/intellij-bitbucket-references-plugin/raw/master/src/main/resources/schemas/bitbucket-pipelines.schema.json

The most notable thing I know of is supporting the `oidc` under steps.

**Comment by sirosen** [comment]
Hi there! I've just released v0.27.3 with updated schemas. Please give it a try and see if it works for you.

Sorry it took ~1 week to get a release out with this. I usually try to offer faster response when people explicitly request a schema update, but wasn't able to deliver that kind of speedy response this time.
