### ISSUE TITLE
Feature request: add file names to the ouptut even if validation is OK

### ISSUE THREAD

**Issue by piotr-kubiak** [python-jsonschema/check-jsonschema#362]
Please consider adding file names to the output, at least when more than one file is being checked.

Setup:
```
[foo@bar ~]$ cat ok1.json
{"name" : "Eggs", "price" : 34.99}

[foo@bar ~]$ cat invalid1.json
{"name" : "Eggs", "price" : "Invalid"}

[foo@bar ~]$ cat schema.json
{
    "type" : "object",
    "properties" : {
        "name" : {"type" : "string"},
        "price" : {"type" : "number"}
    }
}

[foo@bar ~]$ cp ok1.json ok8.json; cp invalid1.json invalid2.json
```

Now let's validate some files:

Example 1:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json ok8.json
ok -- validation done
```

Example 2:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json invalid1.json
Schema validation errors were encountered.
  invalid1.json::$.price: 'Invalid' is not of type 'number'
```
Ok, that was expected. Now let's validate more than one file:

Example 3:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json ok*.json
ok -- validation done
```
So far so good. Let's try invalid files:

Example 4:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json invalid*.json
Schema validation errors were encountered.
  invalid1.json::$.price: 'Invalid' is not of type 'number'
  invalid2.json::$.price: 'Invalid' is not of type 'number'
```
And now let's try all files:

Example 5:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json *.json
Schema validation errors were encountered.
  invalid1.json::$.price: 'Invalid' is not of type 'number'
  invalid2.json::$.price: 'Invalid' is not of type 'number'
```

The problem is, that there is no difference in the last two outputs.
If I look only at the output of the command, I have no indication that files `ok1.json` and `ok8.json` were validated (they can either be skipped or OK). I may have made a typo in the command line, and the output may give me false assumption that my files are OK, when in fact they were skipped (compare Examples 3 and 1: I wanted to write `*` but wrote `8`, the output is the same, but I am mistakenly thinking that all my files were validated and are OK).

It would be helpful if the output provided names of the files that were validated (at least where there is more than one file).

Proposal:
```
[foo@bar ~]$ check-jsonschema --traceback-mode full --schemafile schema.json *.json
  ok1.json: ok -- validation done
  ok8.json: ok -- validation done
Schema validation errors were encountered.
  invalid1.json::$.price: 'Invalid' is not of type 'number'
  invalid2.json::$.price: 'Invalid' is not of type 'number'
```

**Comment by sirosen** [comment]
You can get a full list of all of the files which were checked successfully with the `-v/--verbose` flag.

I'm not interested in making the output longer by default. For cases in which `check-jsonschema` runs over very large numbers of files, this increases output noise.

**Comment by piotr-kubiak** [comment]
OK. I did check if there is `--verbose` option, but found none in the output of `check-jsonschema -h`. However, I was on version 0.13 by mistake. After upgrading to the newset version, the option is available and works as expected. Sorry for the confusion.

**Comment by sirosen** [comment]
No worries!

I closed this because it was phrased as a feature request ("please change this behavior") rather than a question ("can I get this info?"). In the context of the current CLI, with `--verbose` behavior, it seemed like the appropriate response.

I'm always happy to answer questions about `check-jsonschema`. If the helptext and docs site don't provide information that you need, it often means there's an opportunity to clarify!
