### ISSUE TITLE
check-gitlab-ci: coverage is not a regex

### ISSUE THREAD

**Issue by p-rogalski** [python-jsonschema/check-jsonschema#397]
I'm using the `check-gitlab-ci` pre-commit hook to validate `.gitlab-ci.yml` in a Python project.

However, using the [coverage](https://docs.gitlab.com/ee/ci/yaml/index.html#coverage) YAML keyword together with the [recommended RegEx for pytest-cov](https://docs.gitlab.com/ee/ci/testing/code_coverage.html#test-coverage-examples) leads to the following error:

```
Validate GitLab CI config................................................Failed
- hook id: check-gitlab-ci
- exit code: 1

Schema validation errors were encountered.
  .gitlab-ci.yml::$.my-project:test.coverage: '/(?i)total.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/' is not a 'regex'
```

I [pasted the pattern in regex101.com](https://regex101.com/r/cYNwBR/1) and found out that `(?i)` aka inline modifiers are not supported in ECMAScript regex engine, which you use in this project.

A quick fix would be to set the `i` flag for the whole regex:

```
/total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/i
```

However, this is currently not supported by the `gitlab-ci` JSON schema.

Is there anything you can do to fix the problem? Otherwise, I will open an issue over at GitLab to fix the `gitlab-ci` schema accordingly.

**Comment by sirosen** [comment]
You can control the regex engine being used by passing `--format-regex python` to use the Python `re` engine for regex patterns. There's only support for Python `re` and `regress` (a Rust implementation of ECMAScript regexes) today, but I'd be fine with adding others if there are reliable libraries to use.
(By way of example: the Python `regex` package may perform better than `re`, and I might like to build in support for that.)

Under pre-commit, it's just a matter of adding `args`. This should do the trick:
```yaml
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
    - id: check-gitlab-ci
      args: ["--format-regex", "python"]
```

---

But definitely this is an issue with the GItLab schema. JSON Schema (the spec) declares that ECMA Script regex syntax or a strict subset of it -- compatible with most languages/engines -- should be used for regexes.

I'll leave this open until I can cross-link a relevant open ticket on GitLab's tracker.

**Comment by p-rogalski** [comment]
Thanks for your quick reply!

> I just checked the GitLab schema and found that the regex you cited is not the one I see in their schema (or in our vendored copy). What version of check-jsonschema are you using? The latest (0.28.0)?

I`m using version `0.28.0` of *check-jsonschema*. These are the lines in the `gitlab-ci` json schema I'm talking about: https://gitlab.com/gitlab-org/gitlab/-/blob/50724a13fa9bbfdd358079094930e7026c5d48f2/app/assets/javascripts/editor/schema/ci.json?page=2#L1965-L1970

**Comment by p-rogalski** [comment]
> Under pre-commit, it's just a matter of adding args.

I missed that. Unfortunately, this doesn't work either. I will provide you with a minimal reproduction repo shortly!

**Comment by sirosen** [comment]
I misunderstood the original issue -- sorry about this -- from reading the report too quickly.
I thought you were reporting that the `gitlab-ci` schema _contained_ the problematic regex. But actually, it contains a simple regex -- `/.+/` -- which _your_ regex must match.
And that regex comes from gitlab docs.

I'll file a GitLab issue to either correct the schema OR correct their example.
If I had to guess, I would bet they meant for it to be
```
/[Tt]otal.*? (100(?:\\.0+)?\\%|[1-9]?\\d(?:\\.\\d+)?\\%)$/
```

**Comment by sirosen** [comment]
I've filed a gitlab docs issue suggesting the above regex as a docs fix, to see what kind of response I'll get from GitLab:
https://gitlab.com/gitlab-org/gitlab-docs/-/issues/1763

Feel free to :+1: it to signal boost, or just try using that regex and seeing how it works.

**Comment by p-rogalski** [comment]
@sirosen Thank you very much for opening the issue, you certainly have better insight to this!

**Comment by sirosen** [comment]
GitLab has accepted my docs suggestion and their new documented value should validate fine. I've closed out the upstream gitlab bug and I think this is all set. let me know if you see any issues!

**Comment by p-rogalski** [comment]
I tested the new regex and it works as expected, thank you very much for your effort in fixing this. 🚀
