### ISSUE TITLE
Release schemas update?

### ISSUE THREAD

**Issue by nikaro** [python-jsonschema/check-jsonschema#433]
Hello, is it possible to do a release to have this change: https://github.com/python-jsonschema/check-jsonschema/commit/e59be75331d259779d06ea6b8b74d3d06af30967?

I'm using the new `attestations` permissions in GitHub Workflows and my CI (using pre-commit) is broken because the vendored schema is not up-to-date :-)

**Comment by edgarrmondragon** [comment]
+1 no real urgency but it would be nice to have the schema checks pass on our PRs adding attestations

**Comment by sirosen** [comment]
Thanks for the nudge on this, and sorry about the delay!

I kept meaning to do it last week and didn't get to it somehow. I just pushed the new version out. Let me know if you see any issues with it.
