### ISSUE TITLE
Consider using `click` to handle CLI parsing

### ISSUE THREAD

**Issue by sirosen** [python-jsonschema/check-jsonschema#47]
I've been building on `argparse` thusfar and it's... fine. `argparse` is good when the application stays simple enough, but as it grows it gets a bit unwiledy. `click` might suit this better.

`click` provides tab-completion support + a better system for declaring new argument types.
It doesn't handle mutex options out of the box, but I've built a mutex validator on top of it before and it wasn't too hard.

**Comment by ssbarnea** [comment]
I use click on several project but I would not rush in adding it. I kinda doubt the number of command line options is expected to grow much.

As I do not find myself (or others) using the tool more than occasionally from interactive terminals, the benefits of tab-completion might be limited. I bet most users will use it in scripting and CI/CD integration like pre-commit hook, where they do not need completion.
