### ISSUE TITLE
Support running the main module using `python -m check_jsonschema`

### ISSUE THREAD

**Issue by software-opal** [python-jsonschema/check-jsonschema#61]
It would be really nice if I was able to run the CLI using `python3 -m check_jsonschema`.

Currently(version 0.14.0) Python gives this error:
```
$ python3 -m check_jsonschema
/Users/opalsymes/.pyenv/versions/3.10.0/bin/python3: No module named check_jsonschema.__main__; 'check_jsonschema' is a package and cannot be directly executed
```

I tend to use this so it will run with the correct version of python(been burnt too many times with it not doing it)

**Comment by sirosen** [comment]
I've just released v0.14.1 which enables this usage.

Let me know if you see any problems using it! :-)
