### ISSUE TITLE
Add support for native TOML checking of instances

### ISSUE THREAD

**Issue by mondeja** [python-jsonschema/check-jsonschema#95]
Hi, I was reading the thread https://github.com/python-jsonschema/jsonschema/issues/582 and I'm very interested in native TOML instance reading support. Do you still plan to add this, only would be added if other users ask it...? As I'm seeing in the source code, seems to be relatively easy to implement, so let me know if you want some help with it.

Thanks for the great work, cheers!

**Comment by sirosen** [comment]
Yes, I was only planning to add it if someone came along and requested it. It wasn't clear to me in the original thread whether or not anyone wanted TOML specifically, or if it was just being included in the list of other file formats which can be loaded into nested dicts.

Thanks for submitting the issue!

I have some time today to look into this. Although I'm always open to PRs, it might be easier to just wait a little bit.

**Comment by sirosen** [comment]
There's now support for this in `main` -- as expected, it was quite simple.

I would appreciate some additional test data to work against. For the purposes of getting it working, I used [this extremely simple file](https://github.com/python-jsonschema/check-jsonschema/blob/3e74c4affb0bcdf0b323835f9f80e4e94603fefd/tests/example-files/explicit-schema/positive/simple-toml/instance.toml#L1). If there's a more sophisticated case I could add to the acceptance tests, that would be great.

---

I don't plan to release at least until I sort out the type-checking situation with updates to the jsonschema typeshed stubs. Hopefully that's easy for me to knock out shortly.

**Comment by mondeja** [comment]
Thank you! 👍🏼 

> I would appreciate some additional test data to work against. For the purposes of getting it working, I used [this extremely simple file](https://github.com/python-jsonschema/check-jsonschema/blob/3e74c4affb0bcdf0b323835f9f80e4e94603fefd/tests/example-files/explicit-schema/positive/simple-toml/instance.toml#L1). If there's a more sophisticated case I could add to the acceptance tests, that would be great.

Opened #98

**Comment by sirosen** [comment]
I've just released v0.16.0 with support for TOML files if tomli is installed.

Please definitely let me know if you see any issues using it!
